
# EDIT ME by replacing "<project>/<apis-name>" with your image
# Steps to install
# kubectl create serviceaccount installer
# kubectl create clusterrolebinding installer-cluster-admin-binding --clusterrole=cluster-admin --serviceaccount=default:installer
# kubectl create -f install.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: <apis-name>
  labels:
    run: <apis-name>
spec:
  template:
    metadata:
      labels:
        run: <apis-name>
    spec:
      restartPolicy: OnFailure
      serviceAccountName: installer
      containers:
      - args:
        - ./installer
        - --controller-image=gcr.io/<project>/<apis-name>-controller:v1
        - --docs-image=gcr.io/<project>/<apis-name>-docs:v1
        - --name=<apis-name>
        image: gcr.io/<project>/<apis-name>-install:v1
        imagePullPolicy: Always
        name: <apis-name>
