// +build !ignore_autogenerated

// This file was autogenerated by conversion-gen. Do not edit it manually!

package v1alpha2

import (
	idling "github.com/openshift/origin-idler/pkg/apis/idling"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	unsafe "unsafe"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v1alpha2_CrossGroupObjectReference_To_idling_CrossGroupObjectReference,
		Convert_idling_CrossGroupObjectReference_To_v1alpha2_CrossGroupObjectReference,
		Convert_v1alpha2_Idler_To_idling_Idler,
		Convert_idling_Idler_To_v1alpha2_Idler,
		Convert_v1alpha2_IdlerList_To_idling_IdlerList,
		Convert_idling_IdlerList_To_v1alpha2_IdlerList,
		Convert_v1alpha2_IdlerSpec_To_idling_IdlerSpec,
		Convert_idling_IdlerSpec_To_v1alpha2_IdlerSpec,
		Convert_v1alpha2_IdlerStatus_To_idling_IdlerStatus,
		Convert_idling_IdlerStatus_To_v1alpha2_IdlerStatus,
		Convert_v1alpha2_IdlerStatusStrategy_To_idling_IdlerStatusStrategy,
		Convert_idling_IdlerStatusStrategy_To_v1alpha2_IdlerStatusStrategy,
		Convert_v1alpha2_IdlerStrategy_To_idling_IdlerStrategy,
		Convert_idling_IdlerStrategy_To_v1alpha2_IdlerStrategy,
		Convert_v1alpha2_UnidleInfo_To_idling_UnidleInfo,
		Convert_idling_UnidleInfo_To_v1alpha2_UnidleInfo,
	)
}

func autoConvert_v1alpha2_CrossGroupObjectReference_To_idling_CrossGroupObjectReference(in *CrossGroupObjectReference, out *idling.CrossGroupObjectReference, s conversion.Scope) error {
	out.Group = in.Group
	out.Resource = in.Resource
	out.Name = in.Name
	return nil
}

// Convert_v1alpha2_CrossGroupObjectReference_To_idling_CrossGroupObjectReference is an autogenerated conversion function.
func Convert_v1alpha2_CrossGroupObjectReference_To_idling_CrossGroupObjectReference(in *CrossGroupObjectReference, out *idling.CrossGroupObjectReference, s conversion.Scope) error {
	return autoConvert_v1alpha2_CrossGroupObjectReference_To_idling_CrossGroupObjectReference(in, out, s)
}

func autoConvert_idling_CrossGroupObjectReference_To_v1alpha2_CrossGroupObjectReference(in *idling.CrossGroupObjectReference, out *CrossGroupObjectReference, s conversion.Scope) error {
	out.Group = in.Group
	out.Resource = in.Resource
	out.Name = in.Name
	return nil
}

// Convert_idling_CrossGroupObjectReference_To_v1alpha2_CrossGroupObjectReference is an autogenerated conversion function.
func Convert_idling_CrossGroupObjectReference_To_v1alpha2_CrossGroupObjectReference(in *idling.CrossGroupObjectReference, out *CrossGroupObjectReference, s conversion.Scope) error {
	return autoConvert_idling_CrossGroupObjectReference_To_v1alpha2_CrossGroupObjectReference(in, out, s)
}

func autoConvert_v1alpha2_Idler_To_idling_Idler(in *Idler, out *idling.Idler, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha2_IdlerSpec_To_idling_IdlerSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha2_IdlerStatus_To_idling_IdlerStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha2_Idler_To_idling_Idler is an autogenerated conversion function.
func Convert_v1alpha2_Idler_To_idling_Idler(in *Idler, out *idling.Idler, s conversion.Scope) error {
	return autoConvert_v1alpha2_Idler_To_idling_Idler(in, out, s)
}

func autoConvert_idling_Idler_To_v1alpha2_Idler(in *idling.Idler, out *Idler, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_idling_IdlerSpec_To_v1alpha2_IdlerSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_idling_IdlerStatus_To_v1alpha2_IdlerStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_idling_Idler_To_v1alpha2_Idler is an autogenerated conversion function.
func Convert_idling_Idler_To_v1alpha2_Idler(in *idling.Idler, out *Idler, s conversion.Scope) error {
	return autoConvert_idling_Idler_To_v1alpha2_Idler(in, out, s)
}

func autoConvert_v1alpha2_IdlerList_To_idling_IdlerList(in *IdlerList, out *idling.IdlerList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]idling.Idler)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha2_IdlerList_To_idling_IdlerList is an autogenerated conversion function.
func Convert_v1alpha2_IdlerList_To_idling_IdlerList(in *IdlerList, out *idling.IdlerList, s conversion.Scope) error {
	return autoConvert_v1alpha2_IdlerList_To_idling_IdlerList(in, out, s)
}

func autoConvert_idling_IdlerList_To_v1alpha2_IdlerList(in *idling.IdlerList, out *IdlerList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Idler)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_idling_IdlerList_To_v1alpha2_IdlerList is an autogenerated conversion function.
func Convert_idling_IdlerList_To_v1alpha2_IdlerList(in *idling.IdlerList, out *IdlerList, s conversion.Scope) error {
	return autoConvert_idling_IdlerList_To_v1alpha2_IdlerList(in, out, s)
}

func autoConvert_v1alpha2_IdlerSpec_To_idling_IdlerSpec(in *IdlerSpec, out *idling.IdlerSpec, s conversion.Scope) error {
	out.WantIdle = in.WantIdle
	out.TargetScalables = *(*[]idling.CrossGroupObjectReference)(unsafe.Pointer(&in.TargetScalables))
	out.TriggerServiceNames = *(*[]string)(unsafe.Pointer(&in.TriggerServiceNames))
	return nil
}

// Convert_v1alpha2_IdlerSpec_To_idling_IdlerSpec is an autogenerated conversion function.
func Convert_v1alpha2_IdlerSpec_To_idling_IdlerSpec(in *IdlerSpec, out *idling.IdlerSpec, s conversion.Scope) error {
	return autoConvert_v1alpha2_IdlerSpec_To_idling_IdlerSpec(in, out, s)
}

func autoConvert_idling_IdlerSpec_To_v1alpha2_IdlerSpec(in *idling.IdlerSpec, out *IdlerSpec, s conversion.Scope) error {
	out.WantIdle = in.WantIdle
	out.TargetScalables = *(*[]CrossGroupObjectReference)(unsafe.Pointer(&in.TargetScalables))
	out.TriggerServiceNames = *(*[]string)(unsafe.Pointer(&in.TriggerServiceNames))
	return nil
}

// Convert_idling_IdlerSpec_To_v1alpha2_IdlerSpec is an autogenerated conversion function.
func Convert_idling_IdlerSpec_To_v1alpha2_IdlerSpec(in *idling.IdlerSpec, out *IdlerSpec, s conversion.Scope) error {
	return autoConvert_idling_IdlerSpec_To_v1alpha2_IdlerSpec(in, out, s)
}

func autoConvert_v1alpha2_IdlerStatus_To_idling_IdlerStatus(in *IdlerStatus, out *idling.IdlerStatus, s conversion.Scope) error {
	out.Idled = in.Idled
	out.UnidledScales = *(*[]idling.UnidleInfo)(unsafe.Pointer(&in.UnidledScales))
	return nil
}

// Convert_v1alpha2_IdlerStatus_To_idling_IdlerStatus is an autogenerated conversion function.
func Convert_v1alpha2_IdlerStatus_To_idling_IdlerStatus(in *IdlerStatus, out *idling.IdlerStatus, s conversion.Scope) error {
	return autoConvert_v1alpha2_IdlerStatus_To_idling_IdlerStatus(in, out, s)
}

func autoConvert_idling_IdlerStatus_To_v1alpha2_IdlerStatus(in *idling.IdlerStatus, out *IdlerStatus, s conversion.Scope) error {
	out.Idled = in.Idled
	out.UnidledScales = *(*[]UnidleInfo)(unsafe.Pointer(&in.UnidledScales))
	return nil
}

// Convert_idling_IdlerStatus_To_v1alpha2_IdlerStatus is an autogenerated conversion function.
func Convert_idling_IdlerStatus_To_v1alpha2_IdlerStatus(in *idling.IdlerStatus, out *IdlerStatus, s conversion.Scope) error {
	return autoConvert_idling_IdlerStatus_To_v1alpha2_IdlerStatus(in, out, s)
}

func autoConvert_v1alpha2_IdlerStatusStrategy_To_idling_IdlerStatusStrategy(in *IdlerStatusStrategy, out *idling.IdlerStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_v1alpha2_IdlerStatusStrategy_To_idling_IdlerStatusStrategy is an autogenerated conversion function.
func Convert_v1alpha2_IdlerStatusStrategy_To_idling_IdlerStatusStrategy(in *IdlerStatusStrategy, out *idling.IdlerStatusStrategy, s conversion.Scope) error {
	return autoConvert_v1alpha2_IdlerStatusStrategy_To_idling_IdlerStatusStrategy(in, out, s)
}

func autoConvert_idling_IdlerStatusStrategy_To_v1alpha2_IdlerStatusStrategy(in *idling.IdlerStatusStrategy, out *IdlerStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_idling_IdlerStatusStrategy_To_v1alpha2_IdlerStatusStrategy is an autogenerated conversion function.
func Convert_idling_IdlerStatusStrategy_To_v1alpha2_IdlerStatusStrategy(in *idling.IdlerStatusStrategy, out *IdlerStatusStrategy, s conversion.Scope) error {
	return autoConvert_idling_IdlerStatusStrategy_To_v1alpha2_IdlerStatusStrategy(in, out, s)
}

func autoConvert_v1alpha2_IdlerStrategy_To_idling_IdlerStrategy(in *IdlerStrategy, out *idling.IdlerStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_v1alpha2_IdlerStrategy_To_idling_IdlerStrategy is an autogenerated conversion function.
func Convert_v1alpha2_IdlerStrategy_To_idling_IdlerStrategy(in *IdlerStrategy, out *idling.IdlerStrategy, s conversion.Scope) error {
	return autoConvert_v1alpha2_IdlerStrategy_To_idling_IdlerStrategy(in, out, s)
}

func autoConvert_idling_IdlerStrategy_To_v1alpha2_IdlerStrategy(in *idling.IdlerStrategy, out *IdlerStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_idling_IdlerStrategy_To_v1alpha2_IdlerStrategy is an autogenerated conversion function.
func Convert_idling_IdlerStrategy_To_v1alpha2_IdlerStrategy(in *idling.IdlerStrategy, out *IdlerStrategy, s conversion.Scope) error {
	return autoConvert_idling_IdlerStrategy_To_v1alpha2_IdlerStrategy(in, out, s)
}

func autoConvert_v1alpha2_UnidleInfo_To_idling_UnidleInfo(in *UnidleInfo, out *idling.UnidleInfo, s conversion.Scope) error {
	if err := Convert_v1alpha2_CrossGroupObjectReference_To_idling_CrossGroupObjectReference(&in.CrossGroupObjectReference, &out.CrossGroupObjectReference, s); err != nil {
		return err
	}
	out.PreviousScale = in.PreviousScale
	return nil
}

// Convert_v1alpha2_UnidleInfo_To_idling_UnidleInfo is an autogenerated conversion function.
func Convert_v1alpha2_UnidleInfo_To_idling_UnidleInfo(in *UnidleInfo, out *idling.UnidleInfo, s conversion.Scope) error {
	return autoConvert_v1alpha2_UnidleInfo_To_idling_UnidleInfo(in, out, s)
}

func autoConvert_idling_UnidleInfo_To_v1alpha2_UnidleInfo(in *idling.UnidleInfo, out *UnidleInfo, s conversion.Scope) error {
	if err := Convert_idling_CrossGroupObjectReference_To_v1alpha2_CrossGroupObjectReference(&in.CrossGroupObjectReference, &out.CrossGroupObjectReference, s); err != nil {
		return err
	}
	out.PreviousScale = in.PreviousScale
	return nil
}

// Convert_idling_UnidleInfo_To_v1alpha2_UnidleInfo is an autogenerated conversion function.
func Convert_idling_UnidleInfo_To_v1alpha2_UnidleInfo(in *idling.UnidleInfo, out *UnidleInfo, s conversion.Scope) error {
	return autoConvert_idling_UnidleInfo_To_v1alpha2_UnidleInfo(in, out, s)
}
